[package]
name = "sunriseset_parallel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.28.0"
tokio = { version = "1.15.0", features = ["full"] }
rayon = "1.5.1"
array-init = "2.0.0"